server.port=8083

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/pet_management_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.pool-name=PostgresHikariCP

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20

# Kafka Connection Settings
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Kafka Consumer Group IDs
kafka.consumer.group.pet=pet-group
kafka.consumer.group.appointment=appointment-group
kafka.consumer.group.task=task-group
kafka.consumer.group.vaccination=vaccination-group
kafka.consumer.group.owner=owner-group
kafka.consumer.group.resource=resource-group
kafka.consumer.group.notification=notification-group

# Kafka Topic Configuration for Pet Events
kafka.topic.pet.created=pet-created
kafka.topic.pet.updated=pet-updated
kafka.topic.pet.deleted=pet-deleted

# Kafka Topic Configuration for Appointment Events
kafka.topic.appointment.created=appointment-created
kafka.topic.appointment.updated=appointment-updated
kafka.topic.appointment.deleted=appointment-deleted

# Kafka Topic Configuration for Vaccination Reminders
kafka.topic.vaccination.reminder=vaccination-reminder

# Kafka Topic Configuration for Task Events
kafka.topic.task.medical=task-medical
kafka.topic.task.completed=task-completed
kafka.topic.task.emergency=task-emergency
kafka.topic.task.followup=task-followup

# Kafka Topic Configuration for Resource Depletion
kafka.topic.resource.depleted=resource-depleted

# Kafka Topic Configuration for Appointment Task
kafka.topic.task.appointment=task-appointment

# Kafka Topic Configuration for Notification Events
kafka.topic.notification.appointment=notification-appointment
kafka.topic.notification.resource.depletion=notification-resource-depletion

# Kafka Topic Configuration for Owner Events
kafka.topic.owner.created=owner-created

# Feign client configuration
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.retryer.period=100
feign.client.config.default.retryer.maxPeriod=1000
feign.client.config.default.retryer.maxAttempts=3

owner.service.url=localhost:8084
