name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install --file pom.xml -DskipITs

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: mvn test --file pom.xml

  integration-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Start Docker Compose
        run: docker compose -f docker-compose.ci.yml up -d

      - name: Wait for services to be healthy
        run: |
          docker compose -f docker-compose.ci.yml exec mysql mysqladmin --silent --wait=30 ping || exit 1
          docker compose -f docker-compose.ci.yml exec postgres pg_isready || exit 1
          docker compose -f docker-compose.ci.yml exec rabbitmq rabbitmqctl status || exit 1

      - name: Run Integration Tests
        run: mvn verify --file pom.xml

      - name: Stop and remove services
        run: docker compose -f docker-compose.ci.yml down

#  docker-build-and-push:
#    runs-on: ubuntu-latest
#    needs: integration-tests
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Docker
#        uses: docker/setup-buildx-action@v1
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and Push Docker Images
#        run: |
#          docker build -t vetoptim/appointment-service ./appointment-service
#          docker build -t vetoptim/owner-service ./owner-service
#          docker build -t vetoptim/pet-management-service ./pet-management-service
#          docker build -t vetoptim/task-resource-service ./task-resource-service
#          docker push vetoptim/appointment-service
#          docker push vetoptim/owner-service
#          docker push vetoptim/pet-management-service
#          docker push vetoptim/task-resource-service
